<a href="https://colab.research.google.com/github/kimajindk/AIpython/blob/main/250509.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01. Numpy

In [2]:
!pip install numpy
import numpy as np

In [4]:
print(np.__version__)

2.0.2


In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [10]:
c = [1,2,3]

In [13]:
type(a)

numpy.ndarray

In [14]:
type(c)

list

In [15]:
print(np.zeros((2, 3)))      # 2x3 크기의 0 배열
print(np.ones(5))            # 길이 5의 1 배열
print(np.arange(0, 10, 2))   # 0부터 10까지 2씩 증가
print(np.linspace(0, 1, 5))  # 0~1 사이를 5개로 나눈 배열
print(np.random.rand(3))     # 0~1 사이의 난수 3개

[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[0.23480244 0.28073442 0.23519114]


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)    # (2, 3)
print("Data Type:", arr.dtype)  # int64
print("Size:", arr.size)      # 6
print("Dimension:", arr.ndim) # 2

Shape: (2, 3)
Data Type: int64
Size: 6
Dimension: 2


In [17]:
arr = np.array([1, 2, 3, 4, 5])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Min/Max:", np.min(arr), np.max(arr))

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
Min/Max: 1 5


In [27]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 30])  # 30보다 큰 요소만

[40 50]


In [28]:
#문제 1: 다음 조건에 맞는 배열을 생성하고 출력하세요.
#1차원 배열, 5개의 요소, 0으로 초기화된 배열

print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [33]:
#문제 2: 1부터 10까지의 숫자 중 짝수만 포함하는 배열을 생성하세요.
print(np.arange(2, 11, 2))

[ 2  4  6  8 10]


In [30]:
#문제 3: [2, 4, 6] 배열과 [10, 20, 30] 배열을 각각 생성하고, 곱셈 연산을 수행한 결과를 출력하세요.
a = np.array([2, 4, 6])
b = np.array([10, 20, 30])
print(a*b)

[ 20  80 180]


In [31]:
#문제 4: 위 배열에서 20보다 큰 요소만 필터링해서 출력하세요.
c = a*b
print(c[c > 20])

[ 80 180]


In [38]:
a = np.arange(2, 7, 2)
b = np.arange(10, 31, 10)
c = a*b
print(c)

[ 20  80 180]


In [39]:
print(c[c > 20])

[ 80 180]


# 02. Pandas

In [40]:
import pandas as pd

In [45]:
s = pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64


In [51]:
data = {'name': ['홍길동', '김철수', '이영희'],
    'age': [25, 30, 27],
    'sex': ['남', '남', '여']}

df = pd.DataFrame(data)
df

name  age sex
0  홍길동   25   남
1  김철수   30   남
2  이영희   27   여

In [52]:
df.to_csv('output_students.csv', index=False)

In [55]:
df = pd.read_csv('output_students.csv')
print(df.head())  # 처음 5행만 출력

  name  age sex
0  홍길동   25   남
1  김철수   30   남
2  이영희   27   여


In [56]:
#mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [58]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/AI를위한파이썬기초/train_and_test2.csv')
df

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0   
1          0  ...        0        0        0       1        0        0   
2          0  ...        0        0        0       3        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
0          2.0        0        0         0  
1          0.0        0        0         1  
2          2.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
...        ...      ...      ...       ...  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[1309 rows x 28 columns]

In [59]:
df.head()

Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0            1  22.0   7.2500    0      1     0       0       0       0   
1            2  38.0  71.2833    1      1     0       0       0       0   
2            3  26.0   7.9250    1      0     0       0       0       0   
3            4  35.0  53.1000    1      1     0       0       0       0   
4            5  35.0   8.0500    0      0     0       0       0       0   

   zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  Embarked  \
0       0  ...        0        0        0       3        0        0       2.0   
1       0  ...        0        0        0       1        0        0       0.0   
2       0  ...        0        0        0       3        0        0       2.0   
3       0  ...        0        0        0       1        0        0       2.0   
4       0  ...        0        0        0       3        0        0       2.0   

   zero.17  zero.18  2urvived  
0        0        0         0  
1        0        0         1  
2        0        0         1  
3        0        0         1  
4        0        0         0  

[5 rows x 28 columns]

In [60]:
df.tail()

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[5 rows x 28 columns]

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1309 non-null   int64  
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64  
 4   sibsp        1309 non-null   int64  
 5   zero         1309 non-null   int64  
 6   zero.1       1309 non-null   int64  
 7   zero.2       1309 non-null   int64  
 8   zero.3       1309 non-null   int64  
 9   zero.4       1309 non-null   int64  
 10  zero.5       1309 non-null   int64  
 11  zero.6       1309 non-null   int64  
 12  Parch        1309 non-null   int64  
 13  zero.7       1309 non-null   int64  
 14  zero.8       1309 non-null   int64  
 15  zero.9       1309 non-null   int64  
 16  zero.10      1309 non-null   int64  
 17  zero.11      1309 non-null   int64  
 18  zero.12      1309 non-null   int64  
 19  zero.1

In [81]:
#df.dropna(inplace = True) # 원본을 바꾼다

In [83]:
mean = df.mean()
df.fillna(mean)

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0   
1          0  ...        0        0        0       1        0        0   
2          0  ...        0        0        0       3        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
0          2.0        0        0         0  
1          0.0        0        0         1  
2          2.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
...        ...      ...      ...       ...  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[1307 rows x 28 columns]

In [62]:
df.describe()

Passengerid          Age         Fare          Sex        sibsp  \
count  1309.000000  1309.000000  1309.000000  1309.000000  1309.000000   
mean    655.000000    29.503186    33.281086     0.355997     0.498854   
std     378.020061    12.905241    51.741500     0.478997     1.041658   
min       1.000000     0.170000     0.000000     0.000000     0.000000   
25%     328.000000    22.000000     7.895800     0.000000     0.000000   
50%     655.000000    28.000000    14.454200     0.000000     0.000000   
75%     982.000000    35.000000    31.275000     1.000000     1.000000   
max    1309.000000    80.000000   512.329200     1.000000     8.000000   

         zero  zero.1  zero.2  zero.3  zero.4  ...  zero.12  zero.13  zero.14  \
count  1309.0  1309.0  1309.0  1309.0  1309.0  ...   1309.0   1309.0   1309.0   
mean      0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
std       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
min       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
25%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
50%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
75%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
max       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   

            Pclass  zero.15  zero.16     Embarked  zero.17  zero.18  \
count  1309.000000   1309.0   1309.0  1307.000000   1309.0   1309.0   
mean      2.294882      0.0      0.0     1.492731      0.0      0.0   
std       0.837836      0.0      0.0     0.814626      0.0      0.0   
min       1.000000      0.0      0.0     0.000000      0.0      0.0   
25%       2.000000      0.0      0.0     1.000000      0.0      0.0   
50%       3.000000      0.0      0.0     2.000000      0.0      0.0   
75%       3.000000      0.0      0.0     2.000000      0.0      0.0   
max       3.000000      0.0      0.0     2.000000      0.0      0.0   

          2urvived  
count  1309.000000  
mean      0.261268  
std       0.439494  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000  

[8 rows x 28 columns]

In [69]:
df['Age']

0       22.0
1       38.0
2       26.0
3       35.0
4       35.0
        ... 
1304    28.0
1305    39.0
1306    38.5
1307    28.0
1308    28.0
Name: Age, Length: 1309, dtype: float64

In [71]:
df[['Age', 'Fare']]

Age      Fare
0     22.0    7.2500
1     38.0   71.2833
2     26.0    7.9250
3     35.0   53.1000
4     35.0    8.0500
...    ...       ...
1304  28.0    8.0500
1305  39.0  108.9000
1306  38.5    7.2500
1307  28.0    8.0500
1308  28.0   22.3583

[1309 rows x 2 columns]

In [75]:
#행 출력
df.loc[0]

Passengerid     1.00
Age            22.00
Fare            7.25
Sex             0.00
sibsp           1.00
zero            0.00
zero.1          0.00
zero.2          0.00
zero.3          0.00
zero.4          0.00
zero.5          0.00
zero.6          0.00
Parch           0.00
zero.7          0.00
zero.8          0.00
zero.9          0.00
zero.10         0.00
zero.11         0.00
zero.12         0.00
zero.13         0.00
zero.14         0.00
Pclass          3.00
zero.15         0.00
zero.16         0.00
Embarked        2.00
zero.17         0.00
zero.18         0.00
2urvived        0.00
Name: 0, dtype: float64

In [76]:
# 위치 기반 행 선택
df.iloc[0]

Passengerid     1.00
Age            22.00
Fare            7.25
Sex             0.00
sibsp           1.00
zero            0.00
zero.1          0.00
zero.2          0.00
zero.3          0.00
zero.4          0.00
zero.5          0.00
zero.6          0.00
Parch           0.00
zero.7          0.00
zero.8          0.00
zero.9          0.00
zero.10         0.00
zero.11         0.00
zero.12         0.00
zero.13         0.00
zero.14         0.00
Pclass          3.00
zero.15         0.00
zero.16         0.00
Embarked        2.00
zero.17         0.00
zero.18         0.00
2urvived        0.00
Name: 0, dtype: float64

In [80]:
df[df['Age'] >= 34]

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
1               2  38.0   71.2833    1      1     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
6               7  54.0   51.8625    0      0     0       0       0       0   
11             12  58.0   26.5500    1      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1295         1296  43.0   27.7208    0      1     0       0       0       0   
1298         1299  50.0  211.5000    0      1     0       0       0       0   
1302         1303  37.0   90.0000    1      1     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
1          0  ...        0        0        0       1        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
6          0  ...        0        0        0       1        0        0   
11         0  ...        0        0        0       1        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1295       0  ...        0        0        0       1        0        0   
1298       0  ...        0        0        0       1        0        0   
1302       0  ...        0        0        0       1        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
1          0.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
6          2.0        0        0         0  
11         2.0        0        0         1  
...        ...      ...      ...       ...  
1295       0.0        0        0         0  
1298       0.0        0        0         0  
1302       1.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  

[363 rows x 28 columns]

In [87]:
df.groupby('Sex')['Age'].mean()

Sex
0    30.017888
1    28.479720
Name: Age, dtype: float64